[package]
name = "parsoy-project"
version = "0.1.0"
edition = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[dependencies]
toml = "*"

parsoy-config = { workspace = true }